build: false
clone_folder: c:\projects\phpbb

services:
  - mssql2014

init:
  - SET PATH=c:\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET SYMFONY_DEPRECATIONS_HELPER=strict
  - SET ANSICON=121x90 (121x90)
  - SET SYMFONY_PHPUNIT_SKIPPED_TESTS=phpunit.skipped
  - REG ADD "HKEY_CURRENT_USER\Software\Microsoft\Command Processor" /v DelayedExpansion /t REG_DWORD /d 1 /f

before_test:
  - sqlcmd -S "(local)\SQL2014" -Q "Use [master]; CREATE DATABASE [phpbb_test]"
  - SET PATH=C:\Program Files\OpenSSL;C:\tools\php;%PATH%
  - cinst -y php -version 5.6.17 --allow-empty-checksums
  - cd c:\tools\php
  - ps: cat php.ini-production | %{$_ -replace "memory_limit = 128M","memory_limit = 1024M"} | Out-File -Encoding "Default" php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_gd2.dll >> php.ini
  - echo extension=php_tidy.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - php -r "readfile('https://dl.dropboxusercontent.com/u/7129062/sqlsrv_unofficial_3.0.2.2.zip');" > sqlsrv.zip
  - unzip sqlsrv.zip
  - copy sqlsrv_unofficial_3.0.2.2\x64\*.dll ext
  - echo extension=php_sqlsrv_56_nts.dll >> php.ini
  - echo extension=php_pdo_sqlsrv_56_nts.dll >> php.ini
  - cd c:\projects\phpbb\phpBB
  - php ..\composer.phar install
  - cd c:\projects\phpbb\tests
  - touch test_config.php
  - ps: $data = "<?php`n`n`$dbms = 'phpbb\\db\\driver\\mssqlnative';`n`$dbhost = '.\\sql2014';`n`$dbport = '';`n`$dbname = 'phpbb_test';`n`$dbuser = 'sa';`n`$dbpasswd = 'Password12!';"; $data | Out-File -Encoding "Default" "test_config.php"

test_script:
  - cd c:\projects\phpbb
  - php -e phpBB\vendor\phpunit\phpunit\phpunit --verbose --stop-on-error
