build: false
clone_folder: c:\projects\phpbb
version: '{build}'

services:
  - mssql2014
  - iis

hosts:
  phpbb.test: 127.0.0.1

init:
  - SET PATH=c:\php;%PATH%
  - SET ANSICON=121x90 (121x90)
  - REG ADD "HKEY_CURRENT_USER\Software\Microsoft\Command Processor" /v DelayedExpansion /t REG_DWORD /d 1 /f

before_test:
  - sqlcmd -S "(local)\SQL2014" -Q "Use [master]; CREATE DATABASE [phpbb_test]"
  - SET PATH=C:\Program Files\OpenSSL;C:\tools\php;%PATH%
  - cinst -y php -version 5.6.17 --allow-empty-checksums
  - cd c:\tools\php
  - ps: cat php.ini-production | %{$_ -replace "memory_limit = 128M","memory_limit = 1024M"} | Out-File -Encoding "Default" php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo display_errors=On >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_gd2.dll >> php.ini
  - echo extension=php_tidy.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - php -r "readfile('https://dl.dropboxusercontent.com/u/7129062/sqlsrv_unofficial_3.0.2.2.zip');" > sqlsrv.zip
  - unzip sqlsrv.zip
  - copy sqlsrv_unofficial_3.0.2.2\x64\*.dll ext
  - echo extension=php_sqlsrv_56_nts.dll >> php.ini
  - echo extension=php_pdo_sqlsrv_56_nts.dll >> php.ini
  - cd c:\projects\phpbb\phpBB
  - php ..\composer.phar install
  - cd c:\projects\phpbb\tests
  - touch test_config.php
  - ps: $data = "<?php`n`n`$dbms = 'phpbb\\db\\driver\\mssqlnative';`n`$dbhost = '.\\sql2014';`n`$dbport = '';`n`$dbname = 'phpbb_test';`n`$dbuser = 'sa';`n`$dbpasswd = 'Password12!';`n`$phpbb_functional_url = 'http://phpbb.test/';"; $data | Out-File -Encoding "Default" "test_config.php"
  - choco install -y urlrewrite
  - ps: New-WebSite -Name 'phpBBTest' -PhysicalPath 'c:\projects\phpbb\phpBB' -Force
  - ps: Import-Module WebAdministration; Set-ItemProperty 'IIS:\Sites\phpBBTest' -name Bindings -value @{protocol='http';bindingInformation='*:80:phpbb.test'}
  - SET PATH=%systemroot%\system32\inetsrv\;%PATH%
  - echo Change default anonymous user AUTH to ApplicationPool
  - appcmd set config -section:anonymousAuthentication /username:"" --password
  - echo Setup FAST-CGI configuration
  - appcmd set config /section:system.webServer/fastCGI /+[fullPath='C:\tools\php\php-cgi.exe']
  - echo Setup FACT-CGI handler
  - appcmd set config /section:system.webServer/handlers /+[name='PHP-FastCGI',path='*.php',verb='*',modules='FastCgiModule',scriptProcessor='C:\tools\php\php-cgi.exe',resourceType='Either']
  - iisreset
  - NET START W3SVC
  - icacls "C:\projects\phpbb\phpBB\cache" /grant Users:F /T
  - icacls "C:\projects\phpbb\phpBB\files" /grant Users:F /T
  - icacls "C:\projects\phpbb\phpBB\store" /grant Users:F /T
  - icacls "C:\projects\phpbb\phpBB\images\avatars\upload" /grant Users:F /T

test_script:
  - cd c:\projects\phpbb
  - php -e phpBB\vendor\phpunit\phpunit\phpunit --verbose
